version: '3.9'
services:
  frontend:
    image: plavignotte/continuous-curl:latest 
    command: backend_6_02:9000/test
    environment:
      - LOOP=1
    ports:
      - "3000:3000"

  backend:
    build: 
      context: ./backend
      network: host
    container_name: backend_6_02
    ports:
      - "9000:9000"
